### ISSUE TITLE
The #iconForClass:selector: interface went missing

### ISSUE THREAD

**Issue by codeZeilen** [Salami555/Squeak-ToolIconsPlus#1]
Most of the previous calls work well but the message #iconForClass:selector: went missing in the refactoring. It is used, for example, by the Koans.

**Comment by ShirleyNekoDev** [comment]
Das Problem liegt in der falschen Benutzung von iconForClass:selector: - hier wird ein Icon zurückgegeben, anstatt ein Symbol. D.h. das `ToolIcons iconNamed:` ist hier unnötig.

```
KoanStep>>#icon

	^ ToolIcons iconForClass: self chapter selector: self selector
```
